// Generated by BUCKLESCRIPT VERSION 2.2.3, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("bs-platform/lib/js/curry.js");
var Js_exn = require("bs-platform/lib/js/js_exn.js");
var Express = require("bs-express/lib/js/src/Express.js");
var Process = require("process");

var app = Express.express(/* () */0);

Curry._2(Express.App[/* use */0], app, Express.Middleware[/* json */0](/* None */0, /* None */0, /* None */0, /* () */0));

function onListen(e) {
  var exit = 0;
  var val;
  try {
    val = e;
    exit = 1;
  }
  catch (raw_exn){
    var exn = Js_exn.internalToOCamlException(raw_exn);
    if (exn[0] === Js_exn.$$Error) {
      console.log(exn[1]);
      Process.exit(1);
      return /* () */0;
    } else {
      throw exn;
    }
  }
  if (exit === 1) {
    console.log("Listening at http://127.0.0.1:3000");
    return /* () */0;
  }
  
}

var server = Express.App[/* listen */19](app, /* Some */[3000], /* Some */[onListen], /* () */0);

exports.app = app;
exports.onListen = onListen;
exports.server = server;
/* app Not a pure module */
